# Generated by Django 5.0.3 on 2024-07-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assembly', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
