# Generated by Django 5.1.6 on 2025-09-04 15:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("assembly", "0002_uploadedfile_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                blank=True, default="pending", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="uploadedfile",
            name="transcript_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
